name: CI

on:
  push:
    branches:
      - main

jobs:
  build_appbundle:
    name: Build Flutter (Android App Bundle)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle --release --verbose

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

  build_apk:
    name: Build Flutter (APK)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
