name: CI
on:
  push:
    branches:
      - main

jobs:
#  flutter_test:
#    name: Run flutter test and analyze
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "11.x"
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.7.0'
#          channel: 'stable'
#      # Cache dependencies
#      - name: Cache Flutter dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.pub-cache
#          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
#      - run: flutter pub get
#      - run: flutter analyze
#      - run: flutter test

#  build_appbundle:
#    name: Build Flutter (Android App Bundle)
#    needs: [flutter_test]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "11.x"
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.7.0'
#          channel: 'stable'
#      # Cache Gradle dependencies
#      - name: Cache Gradle dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      # Ensure Gradle directory exists and set properties
#      - name: Set Gradle properties
#        run: |
#          mkdir -p ~/.gradle
#          echo "org.gradle.internal.http.socketTimeout=60000" >> ~/.gradle/gradle.properties
#          echo "org.gradle.internal.http.connectionTimeout=60000" >> ~/.gradle/gradle.properties
#          echo "org.gradle.retry=5" >> ~/.gradle/gradle.properties
#
#      - run: flutter pub get
#      - run: flutter clean
#      - run: flutter build appbundle --release --verbose
  build_apk:
    name: Build Flutter (APK)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Clean Flutter and Gradle cache
        run: |
          flutter clean
          rm -rf $HOME/.gradle/caches/

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Ensure Gradle directory exists and set properties
      - name: Set Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.internal.http.socketTimeout=60000" >> ~/.gradle/gradle.properties
          echo "org.gradle.internal.http.connectionTimeout=60000" >> ~/.gradle/gradle.properties
          echo "org.gradle.retry=5" >> ~/.gradle/gradle.properties

      - name: Run flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --verbose || flutter build apk --release --verbose

      - name: Print environment variables
        run: printenv
