name: CI
on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      flutter_version: 3.7.0
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.internal.http.socketTimeout=60000" >> ~/.gradle/gradle.properties
          echo "org.gradle.internal.http.connectionTimeout=60000" >> ~/.gradle/gradle.properties
          echo "org.gradle.retry=5" >> ~/.gradle/gradle.properties

  build_appbundle:
    name: Build Flutter (Android App Bundle)
    needs: [setup_environment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle --release --verbose

  build_apk:
    name: Build Flutter (APK)
    needs: [setup_environment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release --verbose
